### ISSUE TITLE
Tapyrus dependencies upgrade

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#247]
Below table lists the dependency version compared to bitcoin

<div style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; direction: ltr;">

package | tapyrus | Bitcoin( 0.24) | latest
-- | -- | -- | --
bdb | 4.8.30 | 4.8.30 | 18.1
boost | 1.64 | 1.81 |  
dbus | 1.10.18 | -- |  
expat | 2.2.5 | 2.4.8 | Expat 2.5.0
fontconfig | 2.12.1 | 2.12.6 | 2.14.2
freetype | 2.7.1 | 2.11.0 | 2.13.0
libevent | 2.1.8-stable | 2.1.12-stable |  
libICE | 1.0.9 |   |  
libSM | 1.2.2 |   |  
libX11 | 1.6.2 |   |  
libXau | 1.0.8 | 1.0.9 | 1.0.11
libxcb | 1.10 | 1.14 | 1.15
libXext | 1.3.2 |   |  
miniupnpc | 2.0.20180203 | 2.2.2 | 2.2.4
Native_biplist | 1.0.3 |   |  
Native_cctools | 807d6fd1be5d2224872e381870c0a75387fe05e6 | 2ef2e931cf641547eb8a68cfebde61003587c9fd |  
Native_cdrkit | 1.1.11 |   |  
Native_ds_store | 1.1.2 | 1.3.0 | 1.3.0
Native_libdmg-hfsplus | 0.1 |   |  
Native_max_alias | 2.0.7 | 2.2.0 |  
qrencode | 3.4.4 | 3.4.4 | 4.1.1
qt | 5.9.6 | 5.15.5 | 6.2
xcb_proto | 1.10 | 1.14.1 | 1.15
xextproto | 7.3.0 |   |  
xproto | 7.0.26 | 7.0.31 | 7.0.31
xtrans | 1.3.4 |   | 1.4.0
zeromq | 4.2.3 | 4.3.42 |  
zlib | 1.2.11 |   | 1.2.13

**Tasks:**

- [x]  Remove unused libraries
- [x]  Upgrade libs
- [x] Upgrade Tapyrus-builder container
- [ ]  Upgrade macos toolkit

**Comment by Naviabheeman** [comment]
#249 -  Remove unused libraries
#250 #252 #258 #259 #260 - Upgrade other dependencies

**Comment by Naviabheeman** [comment]
Notes for future upgrades:

Qt is built static in bitcoin, non-static in tapyrus

**Macos builds:**
- our cctools and clang are version 6.0.1 (latest version is 14.0.0)
- upgrading config.guess, config.sub cause CONFIGURE failure due to libevent not found. try using sdk 10.15 and cctools 8.0.0
- With sdk 11.0, boost 1.81 build causes lots of deprecated errors. update code to use std:: instead of boost before upgrading sdk.
